# Generated by Django 5.2.4 on 2025-07-29 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productType', models.CharField(max_length=30)),
                ('componentNr', models.IntegerField()),
                ('produs', models.CharField(max_length=30)),
                ('anFabricatie', models.IntegerField()),
                ('nr', models.CharField(max_length=30)),
                ('dimensiuni', models.CharField(max_length=30)),
                ('tip', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SiteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(max_length=30)),
                ('beneficiar', models.CharField(max_length=30)),
                ('locatie', models.CharField(max_length=30)),
                ('nrComanda', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DoorComponentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('number', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='main.doormodel')),
            ],
        ),
        migrations.AddField(
            model_name='doormodel',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='main.sitemodel'),
        ),
    ]
