# Generated by Django 5.2.4 on 2025-08-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doorcomponentmodel',
            old_name='status',
            new_name='verified',
        ),
        migrations.AddField(
            model_name='doorcomponentmodel',
            name='broken',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='doormodel',
            name='titluTabel',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='doorcomponentmodel',
            name='name',
            field=models.CharField(default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='doormodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='sitemodel',
            constraint=models.UniqueConstraint(fields=('beneficiar', 'locatie', 'nrComanda'), name='unique_site_location'),
        ),
    ]
