# Generated by Django 5.2.4 on 2025-08-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_status_doorcomponentmodel_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doormodel',
            name='model',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='doormodel',
            name='nrCanate',
            field=models.IntegerField(default=0),
        ),
    ]
