# Generated by Django 5.2.4 on 2025-09-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_doormodel_model_doormodel_nrcanate'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorcomponentmodel',
            name='nrctr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doormodel',
            name='model',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='doormodel',
            name='nrCanate',
            field=models.CharField(default='', max_length=5),
        ),
    ]
