# Generated by Django 5.2.4 on 2025-09-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_doorcomponentmodel_nrctr_alter_doormodel_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorcomponentmodel',
            name='broken',
            field=models.CharField(default='yes', max_length=30),
        ),
        migrations.AlterField(
            model_name='doorcomponentmodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='doorcomponentmodel',
            name='verified',
            field=models.CharField(default='no', max_length=30),
        ),
    ]
