# Generated by Django 5.2.4 on 2025-09-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_doorcomponentmodel_broken_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doorcomponentmodel',
            old_name='nrctr',
            new_name='nrcrt',
        ),
    ]
