# Generated by Django 5.2.4 on 2025-09-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_nrctr_doorcomponentmodel_nrcrt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorcomponentmodel',
            name='broken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doorcomponentmodel',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
