# Generated by Django 5.2.4 on 2025-09-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_doorcomponentmodel_broken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doormodel',
            name='tip',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
