# Generated by Django 5.2.4 on 2025-09-10 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_doormodel_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='doormodel',
            name='dataInspectiei',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
