# Generated by Django 5.2.4 on 2025-09-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_doormodel_datainspectiei'),
    ]

    operations = [
        migrations.AddField(
            model_name='doormodel',
            name='oras',
            field=models.CharField(default='Timisoara', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doormodel',
            name='tehnician',
            field=models.CharField(default='Teofil Tarniceriu', max_length=30),
            preserve_default=False,
        ),
    ]
