# Generated by Django 5.2.4 on 2025-09-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_doormodel_titlutabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doormodel',
            name='model',
            field=models.CharField(default='', max_length=5, null=True),
        ),
    ]
