# Generated by Django 5.2.4 on 2025-09-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_doormodel_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doormodel',
            name='model',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
    ]
