# Generated by Django 5.2.4 on 2025-09-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_doormodel_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doormodel',
            name='dataInspectiei',
            field=models.DateField(),
        ),
    ]
