# Generated by Django 5.2.4 on 2025-09-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_doormodel_datainspectiei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doormodel',
            name='dataInspectiei',
            field=models.DateTimeField(),
        ),
    ]
