# Generated by Django 5.2.4 on 2025-09-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_doormodel_datainspectiei'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemodel',
            name='exported',
            field=models.BooleanField(default=False),
        ),
    ]
