# Generated by Django 5.2.4 on 2025-09-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_sitemodel_exported'),
    ]

    operations = [
        migrations.AddField(
            model_name='doormodel',
            name='informare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doormodel',
            name='lipsuri',
            field=models.BooleanField(default=False),
        ),
    ]
