# Generated by Django 5.2.4 on 2025-09-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_doormodel_informare_doormodel_lipsuri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doormodel',
            name='oras',
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='oras',
            field=models.CharField(default='Timisoara', max_length=30),
            preserve_default=False,
        ),
    ]
